### ISSUE TITLE
Sage API Multithreading

### ISSUE THREAD

**Issue by BrnPer** [sage-portugal/50c-API#27]
Hi Sage Team,

I was doing some tests with the API for Sage 2022 and I noticed that I was having some problems related to a specific DLL.

After a lot of research, testing and even using this project, I realized that the problem was because of the STAThread attribute in the application startup. This attribute makes the application run in a single thread. That's what you've in your project.

Is there a way to not use this attribute and allow an application that uses multithreading to use your API?

Thanks for your help.

**Comment by ajteixeira** [comment]
At present day, STAThread is intended and mandatory, sorry.
