### ISSUE TITLE
Properties.PropertyID1

### ISSUE THREAD

**Issue by mesofranico** [sage-portugal/50c-API#45]
Para termos o valor da Propriedade na API usa Detail.ItemProperties.PropertyID1 = item.PropertyID1;

Mas quando queremos usar os valores que eu marquei na imagem em anexo, como poderia fazer? Obg

![prop](https://github.com/sage-portugal/50c-API/assets/8009556/c64f0a32-7e08-4f8e-9a81-2e2bd18b60e0)

**Comment by marcosacramento** [comment]
O PropertyID1 é o nome da propriedade 1, o PropertyValue1 é o valor efetivo da propriedade.

Para utilizar uma propriedade com a segunda e 3ª chave deve fazer o seguinte:

Detail.ItemProperties.PropertyValue1 = valor_propriedade;
Detail.ItemProperties.PropertyValue1_Key2 = chave2;
Detail.ItemProperties.PropertyValue1_Key3 = chave3;

Para obter os detalhes da propriedade
1. Vamos buscar a mesma:
ItemProperty _property = dsoCache.ItemPropertyProvider.GetItemProperty(nomepropriedade);

2. Validamos se utiliza chaves;
bool usa_chave2 = _property.AskForKey2;
bool usa_chave3 = _property.AskForKey3;

3. Obtemos o nome das chaves:
string nome_chave2 = _property.KeyDescription2;
string nome_chave3 = _property.KeyDescription3;

Espero ter ajudado.

**Comment by mesofranico** [comment]
Excelente muito obrigado
